### ISSUE TITLE
UI in Node-Red bauen

### ISSUE THREAD

**Issue by pschm** [Archi-Lab-FAE/fae-team-2-documentation#18]
**Sobald fertig: Code mit in das Service Repo laden.**

code: https://node-red.fae.archi-lab.io/#flow/d5ac30bb.ee466

ui: https://node-red.fae.archi-lab.io/ui/#!/1?socketid=BqWx7NwqfyQ8CvKmAAAV

Flows sollten auch auf GitHub persistiert werden. (Export im Editor)

Alle Szenarios müssen abgebildet sein: https://archi-lab.io/display/public/03+-+Integration+Scenarios+For+Case+Study

**Comment by sheila62** [comment]
Alle Szenarien abgebildet (Zone definieren, Zone aktualisieren).
Offene Punkte:
- was ist mit Get Zone via id
- welche url
- wie bekomme ich beim Post die Informationen übertragen z.B. die Positionen der Zone?
- fehlerhafter Output bei aktualisierung der Zone 
- Github persistenz: export im Editor ?!

**Comment by RedAvenge** [comment]
Wurde zwar per Mail rum geschickt, aber hier noch einmal um es schneller zu finden. Das muss gemacht werden:
https://www.archi-lab.io/display/public/03+-+Integration+Scenarios+For+Case+Study

**Comment by pschm** [comment]
Einbinden eines Beispiel Demos für die draußen Ortung. Ggf. ein großes Rechteck über DE packen. Und die Außnahme bekommt Koordinaten aus UK, ...

Es können direkt JSONs hinterlegt werden. Theoretisch reichen zwei Buttons aus. Zone DE anlegen + ausreißer nach UK.

+1 Btn für Zonenausreißer Belgien (nah)
+1 Zone aktualisieren (Rechteck ist jetzt über DE und Benelux)
+1 Btn für Busfahrt nach Spanien. (macht ggf. das gleiche wie der erste Btn und ist nur für den besseren Ablauf vorhanden)
