### ISSUE TITLE
Code aus .yaml generieren

### ISSUE THREAD

**Issue by pschm** [Archi-Lab-FAE/fae-team-2-documentation#19]

**Comment by RedAvenge** [comment]
Habe die aip yaml angepasst von wegen Ids sind keine Zahlen mehr.
Habe auch mal den generierten Code in unsere Service Implementierung gezogen und das Resultat auch im git auf einen neuen Branch "openapi" gepushed.

Hat den Grund, da nach dem auto-gen-code kopieren folgende Fragen offen sind:
- Lassen wir die package-Struktur so, wie sie der Generator ausgespuckt hat? Also nicht nach Enitiy sortiert, sondern nach Funktionalität
- Wie machen wir das mit den Datenbank-Enitiy-Klassen? Die Swagger-Klassen sind ja bereits sehr voll mit Code und Annotationen. Sollen bzw. Sollte man diese dann noch um die z.B. @Id und @OneToMany Sachen erweitern oder wie gehen wir damit nun um?
- Schreiben wir die Logig der Endpunkte wieder direkt in den Controller rein (so wie es jz auch ist) oder machen wir extra Service-Klassen dafür fertig?
- Der generierte Code hat manche Klassen (glaub 1 oder 2), die sehr viele Sonar-Lint Code-Smells verursachen. Da müssten wir mal gucken, ob man die ggf. reinfach rausnehmen kann oder ob das "ok" ist (dann aber klären mit Bente oder so), da die auto-gen sind.

Ach so und nicht Wunder: Ich habe noch KEINE Logig der Endpunkte in den generierten Code übernommen. Die alten Klassen sind in dem Ordner "OLD-Classes", außerhalb des src-Ordners, gelandet.

**Comment by pschm** [comment]
> Lassen wir die package-Struktur so, wie sie der Generator ausgespuckt hat? Also nicht nach Enitiy sortiert, sondern nach Funktionalität

Ich finde beide Varianten gut, wenn wir es bei der Einteilung nach Funktionalität belassen, würde ich allerdings noch das api package weiter Einteilen. Also Controller, APIs und Hilfklassen jeweils zusammenfassen.
**EDIT**: Nach Einbindung von Kafka und in mit der Überlegung noch Dto Objekte einzubinden, denke ich, dass eine Package-Struktur nach Entitäten übersichtlicher ist und würde dafür plädieren.

> Wie machen wir das mit den Datenbank-Enitiy-Klassen? Die Swagger-Klassen sind ja bereits sehr voll mit Code und Annotationen. Sollen bzw. Sollte man diese dann noch um die z.B. @id und @OneToMany Sachen erweitern oder wie gehen wir damit nun um?

Bleibt uns etwas anderes übrig, als die Entitäten mit weiteren Annotationen zu erweitern? Mir ist spontan keine andere schöne Umsetzungsmöglichkeit bekannt.

> Schreiben wir die Logik der Endpunkte wieder direkt in den Controller rein (so wie es jz auch ist) oder machen wir extra Service-Klassen dafür fertig?

Für die meisten Endpunkte wäre eine extra Service-Klasse overkill. Daher wäre mein Vorschlag, erst einmal auf Service-Klassen zu verzichten. Sollten bei der Implementierung der komplexeren Endpunkte die Kontroller sehr unübersichtlich werden, können die Service-Klassen nachträglich eingebaut werden.
**EDIT**: Ich hatte mich dort auch versucht dran zu setzten, konnte aber noch nicht feststellen, wie ich die Repositorys in den Controllers zur Verfügung stelle. **Jemand eine Idee?**

> Der generierte Code hat manche Klassen (glaub 1 oder 2), die sehr viele Sonar-Lint Code-Smells verursachen. Da müssten wir mal gucken, ob man die ggf. reinfach rausnehmen kann oder ob das "ok" ist (dann aber klären mit Bente oder so), da die auto-gen sind.

Von dem was ich jetzt gesehen habe, beläuft sich ein Großteil der Smells auf die fehlende Nutzung von Lambda-Ausdrücken. Sollte also möglich sein diese zu beseitigen. Wenn etwas übrig bleibt, was nicht beseitig werden kann, können wir dies immer noch mit Bente und Co. besprechen.
