### ISSUE TITLE
Business Logik

### ISSUE THREAD

**Issue by pschm** [Archi-Lab-FAE/fae-team-2-documentation#21]
Alle Endpunkte anbieten, die in der High-Level-Api definition definiert sind.
Test für die Logik gehören dazu.

Ggf. Decision festlegen, oder Glossary ändern, wenn sich auf ein normales Rechteck beschränkt wird.

Abhängigkeit: #20

**Comment by RedAvenge** [comment]
Unter anderem ist ein TODO mit Platzhalter, an der Stelle, wo noch Logik hin muss, in der "PositionssenderApiController"-Klasse.

Sinnvoll wäre es auch, Tests für die Business-Logik zu schreiben, ähnlich wie in #22
