### ISSUE TITLE
Test für CRUD Entitys schreiben

### ISSUE THREAD

**Issue by pschm** [Archi-Lab-FAE/fae-team-2-documentation#22]
Jeder einen Endpunkt
- Demenziell Erkankter -> @pschm 
- Positionssender -> @sheila62 
- Zone -> @RedAvenge

**Comment by sheila62** [comment]
Positionssender Done

**Comment by RedAvenge** [comment]
Für Zone ist jetzt auch drin.
Zusätzlich zum Controller habe ich auch einen Test für das ZonenRepository und Tests für die convert und update-Mehoden in der Zonenklasse eingebaut.

**Comment by pschm** [comment]
Auch für Demenziell Erkrankte drin.

Wie bereits besprochen sollten wir noch eine Decision festhalten, wie die Test benannt werden. (Ggf. heute nach/vor/während der Veranstaltung)

**Comment by pschm** [comment]
TODO entsprechend der [decision](https://github.com/Archi-Lab-FAE/fae-team-2-documentation/blob/master/2020-01-10-Decision-Namensgebung-der-Testklassen.md) anpassen.

**Comment by pschm** [comment]
Demenziell Erkrankte sind jetzt auf einer Testabdeckung von 97%, ich denke dass sollte erstmal reichen :)
das kafka Package konnte ich dadurch auch auf 94% bekommen.
