### ISSUE TITLE
Quality-Checks wieder einschalten

### ISSUE THREAD

**Issue by RedAvenge** [Archi-Lab-FAE/fae-team-2-documentation#27]
SonarQube in der jenkins-file wieder einschalten.

Am besten aber erst dann, wenn der ms in Jenkins einmal durchgelaufen ist und von außen erreichbar ist.

**Comment by pschm** [comment]
Am 26.01.2020 wieder einkommentieren.

**Comment by RedAvenge** [comment]
Checks sind wieder aktiviert, das Quality-Gate (welches den Build abbrechen würde) noch nicht

**Comment by pschm** [comment]
Gate ist aktiviert und läuft.
