### ISSUE TITLE
REST-Call an Team3

### ISSUE THREAD

**Issue by pschm** [Archi-Lab-FAE/fae-team-2-documentation#34]

**Comment by pschm** [comment]
Adressee auf PROD wahrscheinlich: fae-team-3-service

Siehe [application.yaml](https://github.com/Archi-Lab-FAE/fae-team-3-service/blob/master/src/main/resources/application.yml) von Team 3

**Comment by RedAvenge** [comment]
Siehe [Swagger-UI](https://api.fae.archi-lab.io/team-3/swagger-ui/index.html?url=/team-3/v3/api-docs#/Ausnahmesituation/createAusnahmesituation) von Team 3
