### ISSUE TITLE
Weitere Decisions anlegen, siehe Svens Notizen. 

### ISSUE THREAD

**Issue by pschm** [Archi-Lab-FAE/fae-team-2-documentation#47]

**Comment by RedAvenge** [comment]
**Info:** Das sind nur Notizen, nicht jede Notiz muss zwingend eine Decision wert sein!

|  Was | Wer  |
| ------------ | ------------ |
|  git-vorgehen (Nur master, keine branches, Warum) |  @sheila62  |
|  Warum nicht an die Linie in IntelliJ gehalten für Zeilenlänge |  @sheila62  |
|  Entscheidung DTO (Trennung Entity und Auto-Gen-Code) | @RedAvenge   |
|  Entscheidung, dass wir alle CRUDS auch als REST anbieten | @pschm  |
|  Entscheidung wie Team-Abstimmungen gemacht werden/wurden | @pschm  |
|  Entscheidung Kafka-Events in Repo zu speichern |  @pschm |
|  Entscheidung API-First | @RedAvenge   |
|  Entscheidung, dass Vorlesung nicht in Zeiterfassung drin ist? |  @pschm |
|  Entscheidung SampleDataLoader  | @sheila62   |
|  Wo liegt Node-Red-Backup? (Keine Decision, eher Wiki oder so) | @RedAvenge   |
| Package-Strucktur | @RedAvenge  |
