### ISSUE TITLE
Heimbewohner aus Domain Model und Code rausnehmen

### ISSUE THREAD

**Issue by pschm** [Archi-Lab-FAE/fae-team-2-documentation#9]

**Comment by pschm** [comment]
Nach erneuter Diskussion, bleibt der Heimbewohner Teil des Models, da eine Person mehrere GPS-Sender haben kann und diese die gleichen Zonen haben sollten.

**Comment by pschm** [comment]
Decision ist festgehalten und Code entsprechend der Glossarbegriffe aktualisiert.

**Comment by RedAvenge** [comment]
Bild auch angepasst.
